kamus_kandungan_terjemahan = {
    # Existing entries
    'asam folat': 'folic acid',
    'asam mefenamat': 'mefenamic acid',
    'asam traneksamat': 'tranexamic acid',
    'atenolol': 'atenolol',
    'betahistin': 'betahistine',
    'cetirizine': 'cetirizine',
    'ciprofloxacin': 'ciprofloxacin',
    'clobazam': 'clobazam',
    'clopidogrel': 'clopidogrel',
    'dexametason': 'dexamethasone',
    'diclofenac': 'diclofenac',
    'diphenhydramine': 'diphenhydramine',
    'domperidone': 'domperidone',
    'fenofibrate': 'fenofibrate',
    'flunarizin': 'flunarizine',
    'glibenklamid': 'glyburide',
    'ibuprofen': 'ibuprofen',
    'isosorbid dinitrat': 'isosorbide dinitrate',
    'isosorbid mononitrat': 'isosorbide mononitrate',
    'ketoprofen': 'ketoprofen',
    'klozapin': 'clozapine',
    'loratadin': 'loratadine',
    'meloxicam': 'meloxicam',
    'metformin': 'metformin',
    'methylprednisolone': 'methylprednisolone',
    'metoclopramide': 'metoclopramide',
    'nifedipin': 'nifedipine',
    'nimesulide': 'nimesulide',
    'omeprazol': 'omeprazole',
    'paracetamol': 'acetaminophen',
    'piroxicam': 'piroxicam',
    'propranolol': 'propranolol',
    'ranitidin': 'ranitidine',
    'simvastatin': 'simvastatin',
    'spironolakton': 'spironolactone',
    'sukralfat': 'sucralfate',
    'tramadol': 'tramadol',
    
    # New entries based on your data
    'metamizole and diazepam': 'metamizole diazepam',
    'sulodexide': 'sulodexide',
    'flunarizine': 'flunarizine',
    'vitamin b complex': 'vitamin b complex',
    'diclofenac potassium': 'diclofenac potassium',
    'chlordiazepoxide and clidinium': 'chlordiazepoxide clidinium',
    'amlodipin tab': 'amlodipine',
    'ranitidine': 'ranitidine',
    'methylprednisolone': 'methylprednisolone',
    'nimesulide': 'nimesulide',
    'lansoprazole': 'lansoprazole',
    'omeprazole': 'omeprazole',
    'sucralfate': 'sucralfate',
    'dexamethasone': 'dexamethasone',
    'bromhexine': 'bromhexine',
    'tranexamic acid': 'tranexamic acid',
    'diphenhydramine': 'diphenhydramine',
    'trimethoprim and sulfamethoxazole': 'trimethoprim sulfamethoxazole',
    'attapulgite': 'attapulgite',
    'terazosin': 'terazosin',
    'piroxicam': 'piroxicam',
    'dexketoprofen': 'dexketoprofen',
    'echinacea zinc vitamin c': 'echinacea zinc vitamin c',
    'levofloxacin': 'levofloxacin',
    'paracetamol': 'acetaminophen',
    'dipyridamole': 'dipyridamole',
    'mecobalamin': 'mecobalamin',
    'meloxicam': 'meloxicam',
    'flavoxate': 'flavoxate',
    'phenobarbital': 'phenobarbital',
    'chloramphenicol ophthalmic': 'chloramphenicol ophthalmic',
    'succus liquiritiae ammonium chloride ephedrine hcl chlorpheniramine maleate paracetamol': 'succus liquiritiae ammonium chloride ephedrine hcl chlorpheniramine maleate paracetamol',
    'paracetamol phenylpropanolamine dexchlorpheniramine dextromethorphan guaifenesin': 'paracetamol phenylpropanolamine dexchlorpheniramine dextromethorphan guaifenesin',
    'dextromethorphan diphenhydramine ammonium chloride': 'dextromethorphan diphenhydramine ammonium chloride',
    'phenitoin': 'phenytoin',
    'amlodipine': 'amlodipine',
    'levodopa': 'levodopa',
    'benserazide': 'benserazide',
    'clidinium': 'clidinium',
    'chlordiazepoxide': 'chlordiazepoxide',
    'diazepam': 'diazepam',
    'amitriptyline': 'amitriptyline',
    'caffeine': 'caffeine',
    'guaifenesin': 'guaifenesin',
    'ephedrine': 'ephedrine',
    'chlorpheniramine': 'chlorpheniramine',
    'ammonium chloride': 'ammonium chloride',
    'dextromethorphan': 'dextromethorphan',
    'phenylephrine': 'phenylephrine',
    'pseudoephedrine': 'pseudoephedrine',
    'triprolidine': 'triprolidine',
    'hydroxyzine': 'hydroxyzine',
    'promethazine': 'promethazine',
    'codeine': 'codeine',
    'hydrocodone': 'hydrocodone',
    'oxycodone': 'oxycodone',
    'morphine': 'morphine',
    'fentanyl': 'fentanyl',
    'pethidine': 'pethidine',
    'pentazocine': 'pentazocine',
    'buprenorphine': 'buprenorphine',
    'nalbuphine': 'nalbuphine',
    'tramadol': 'tramadol',
    'tapentadol': 'tapentadol',
    'celecoxib': 'celecoxib',
    'etoricoxib': 'etoricoxib',
    'valdecoxib': 'valdecoxib',
    'parecoxib': 'parecoxib',
    'rofecoxib': 'rofecoxib',
    'lumiracoxib': 'lumiracoxib',
    'indomethacin': 'indomethacin',
    'aceclofenac': 'aceclofenac',
    'etodolac': 'etodolac',
    'nabumetone': 'nabumetone',
    'tenoxicam': 'tenoxicam',
    'loxoprofen': 'loxoprofen',
    'mefenamic acid': 'mefenamic acid',
    'flurbiprofen': 'flurbiprofen',
    'ketorolac': 'ketorolac',
    'piroxicam': 'piroxicam',
    'meclofenamate': 'meclofenamate',
    'sulindac': 'sulindac',
    'tolmetin': 'tolmetin',
    'fenoprofen': 'fenoprofen',
    'oxaprozin': 'oxaprozin',
    'naproxen': 'naproxen',
    'diclofenac sodium': 'diclofenac sodium',
    'diclofenac potassium': 'diclofenac potassium',
    'diclofenac misoprostol': 'diclofenac misoprostol',
    'diclofenac epolamine': 'diclofenac epolamine',
    'diclofenac diethylamine': 'diclofenac diethylamine',
    'diclofenac resinate': 'diclofenac resinate',
    'diclofenac hydroxyethylpyrrolidine': 'diclofenac hydroxyethylpyrrolidine',
    'diclofenac diethylammonium': 'diclofenac diethylammonium',
    'diclofenac sodium and misoprostol': 'diclofenac sodium misoprostol',
    'diclofenac potassium and misoprostol': 'diclofenac potassium misoprostol',
    'diclofenac sodium and lidocaine': 'diclofenac sodium lidocaine',
    'diclofenac potassium and lidocaine': 'diclofenac potassium lidocaine',
    'diclofenac sodium and thiocolchicoside': 'diclofenac sodium thiocolchicoside',
    'diclofenac potassium and thiocolchicoside': 'diclofenac potassium thiocolchicoside',
    'diclofenac sodium and paracetamol': 'diclofenac sodium paracetamol',
    'diclofenac potassium and paracetamol': 'diclofenac potassium paracetamol',
    'diclofenac sodium and serratiopeptidase': 'diclofenac sodium serratiopeptidase',
    'diclofenac potassium and serratiopeptidase': 'diclofenac potassium serratiopeptidase',
    'diclofenac sodium and chlorzoxazone': 'diclofenac sodium chlorzoxazone',
    'diclofenac potassium and chlorzoxazone': 'diclofenac potassium chlorzoxazone',
    'diclofenac sodium and tizanidine': 'diclofenac sodium tizanidine',
    'diclofenac potassium and tizanidine': 'diclofenac potassium tizanidine',
    'diclofenac sodium and methocarbamol': 'diclofenac sodium methocarbamol',
    'diclofenac potassium and methocarbamol': 'diclofenac potassium methocarbamol',
    'diclofenac sodium and orphenadrine': 'diclofenac sodium orphenadrine',
    'diclofenac potassium and orphenadrine': 'diclofenac potassium orphenadrine',
    'diclofenac sodium and baclofen': 'diclofenac sodium baclofen',
    'diclofenac potassium and baclofen': 'diclofenac potassium baclofen',
    'diclofenac sodium and cyclobenzaprine': 'diclofenac sodium cyclobenzaprine',
    'diclofenac potassium and cyclobenzaprine': 'diclofenac potassium cyclobenzaprine',
    'diclofenac sodium and carisoprodol': 'diclofenac sodium carisoprodol',
    'diclofenac potassium and carisoprodol': 'diclofenac potassium carisoprodol',
    'diclofenac sodium and metaxalone': 'diclofenac sodium metaxalone',
    'diclofenac potassium and metaxalone': 'diclofenac potassium metaxalone',
    'diclofenac sodium and eperisone': 'diclofenac sodium eperisone',
    'diclofenac potassium and eperisone': 'diclofenac potassium eperisone',
    'diclofenac sodium and tolperisone': 'diclofenac sodium tolperisone',
    'diclofenac potassium and tolperisone': 'diclofenac potassium tolperisone',
    'diclofenac sodium and thiocolchicoside': 'diclofenac sodium thiocolchicoside',
    'diclofenac potassium and thiocolchicoside': 'diclofenac potassium thiocolchicoside',
    'diclofenac sodium and aceclofenac': 'diclofenac sodium aceclofenac',
    'diclofenac potassium and aceclofenac': 'diclofenac potassium aceclofenac',
    'diclofenac sodium and nimesulide': 'diclofenac sodium nimesulide',
    'diclofenac potassium and nimesulide': 'diclofenac potassium nimesulide',
    'diclofenac sodium and paracetamol': 'diclofenac sodium paracetamol',
    'diclofenac potassium and paracetamol': 'diclofenac potassium paracetamol',
    'diclofenac sodium and tramadol': 'diclofenac sodium tramadol',
    'diclofenac potassium and tramadol': 'diclofenac potassium tramadol',
    'diclofenac sodium and codeine': 'diclofenac sodium codeine',
    'diclofenac potassium and codeine': 'diclofenac potassium codeine',
    'diclofenac sodium and caffeine': 'diclofenac sodium caffeine',
    'diclofenac potassium and caffeine': 'diclofenac potassium caffeine',
    'diclofenac sodium and serratiopeptidase': 'diclofenac sodium serratiopeptidase',
    'diclofenac potassium and serratiopeptidase': 'diclofenac potassium serratiopeptidase',
    'diclofenac sodium and trypsin chymotrypsin': 'diclofenac sodium trypsin chymotrypsin',
    'diclofenac potassium and trypsin chymotrypsin': 'diclofenac potassium trypsin chymotrypsin',
    'diclofenac sodium and bromelain': 'diclofenac sodium bromelain',
    'diclofenac potassium and bromelain': 'diclofenac potassium bromelain',
    'diclofenac sodium and rutoside': 'diclofenac sodium rutoside',
    'diclofenac potassium and rutoside': 'diclofenac potassium rutoside',
    'diclofenac sodium and vitamin B complex': 'diclofenac sodium vitamin B complex',
    'diclofenac potassium and vitamin B complex': 'diclofenac potassium vitamin B complex',
    'diclofenac sodium and methylcobalamin': 'diclofenac sodium methylcobalamin',
    'diclofenac potassium and methylcobalamin': 'diclofenac potassium methylcobalamin',
    'diclofenac sodium and alpha lipoic acid': 'diclofenac sodium alpha lipoic acid',
    'diclofenac potassium and alpha lipoic acid': 'diclofenac potassium alpha lipoic acid',
    'diclofenac sodium and gabapentin': 'diclofenac sodium gabapentin',
    'diclofenac potassium and gabapentin': 'diclofenac potassium gabapentin',
    'diclofenac sodium and pregabalin': 'diclofenac sodium pregabalin',
    'diclofenac potassium and pregabalin': 'diclofenac potassium pregabalin',
    'diclofenac sodium and amitriptyline': 'diclofenac sodium amitriptyline',
    'diclofenac potassium and amitriptyline': 'diclofenac potassium amitriptyline',
    'diclofenac sodium and nortriptyline': 'diclofenac sodium nortriptyline',
    'diclofenac potassium and nortriptyline': 'diclofenac potassium nortriptyline',
    'diclofenac sodium and imipramine': 'diclofenac sodium imipramine',
    'diclofenac potassium and imipramine': 'diclofenac potassium imipramine',
    'diclofenac sodium and doxepin': 'diclofenac sodium doxepin',
    'diclofenac potassium and doxepin': 'diclofenac potassium doxepin',
    'diclofenac sodium and clomipramine': 'diclofenac sodium clomipramine',
    'diclofenac potassium and clomipramine': 'diclofenac potassium clomipramine',
    'diclofenac sodium and fluoxetine': 'diclofenac sodium fluoxetine',
    'diclofenac potassium and fluoxetine': 'diclofenac potassium fluoxetine',
    'diclofenac sodium and sertraline': 'diclofenac sodium sertraline',
    'diclofenac potassium and sertraline': 'diclofenac potassium sertraline',
    'diclofenac sodium and paroxetine': 'diclofenac sodium paroxetine',
    'diclofenac potassium and paroxetine': 'diclofenac potassium paroxetine',
    'diclofenac sodium and escitalopram': 'diclofenac sodium escitalopram',
    'diclofenac potassium and escitalopram': 'diclofenac potassium escitalopram',
    'diclofenac sodium and citalopram': 'diclofenac sodium citalopram',
    'diclofenac potassium and citalopram': 'diclofenac potassium citalopram',
    'diclofenac sodium and venlafaxine': 'diclofenac sodium venlafaxine',
    'diclofenac potassium and venlafaxine': 'diclofenac potassium venlafaxine',
    'diclofenac sodium and duloxetine': 'diclofenac sodium duloxetine',
    'diclofenac potassium and duloxetine': 'diclofenac potassium duloxetine',
    'diclofenac sodium and mirtazapine': 'diclofenac sodium mirtazapine',
    'diclofenac potassium and mirtazapine': 'diclofenac potassium mirtazapine',
    'diclofenac sodium and bupropion': 'diclofenac sodium bupropion',
    'diclofenac potassium and bupropion': 'diclofenac potassium bupropion',
    'diclofenac sodium and trazodone': 'diclofenac sodium trazodone',
    'diclofenac potassium and trazodone': 'diclofenac potassium trazodone',
    'diclofenac sodium and nefazodone': 'diclofenac sodium nefazodone',
    'diclofenac potassium and nefazodone': 'diclofenac potassium nefazodone',
    'diclofenac sodium and vilazodone': 'diclofenac sodium vilazodone',
    'diclofenac potassium and vilazodone': 'diclofenac potassium vilazodone',
    'diclofenac sodium and vortioxetine': 'diclofenac sodium vortioxetine',
    'diclofenac potassium and vortioxetine': 'diclofenac potassium vortioxetine',
    'diclofenac sodium and agomelatine': 'diclofenac sodium agomelatine',
    'diclofenac potassium and agomelatine': 'diclofenac potassium agomelatine',
    'diclofenac sodium and tianeptine': 'diclofenac sodium tianeptine',
    'diclofenac potassium and tianeptine': 'diclofenac potassium tianeptine',
    'diclofenac sodium and milnacipran': 'diclofenac sodium milnacipran',
    'diclofenac potassium and milnacipran': 'diclofenac potassium milnacipran',
    'diclofenac sodium and levomilnacipran': 'diclofenac sodium levomilnacipran',
    'diclofenac potassium and levomilnacipran': 'diclofenac potassium levomilnacipran',
    'diclofenac sodium and reboxetine': 'diclofenac sodium reboxetine',
    'diclofenac potassium and reboxetine': 'diclofenac potassium reboxetine',
    'diclofenac sodium and atomoxetine': 'diclofenac sodium atomoxetine',
    'diclofenac potassium and atomoxetine': 'diclofenac potassium atomoxetine',
    'diclofenac sodium and modafinil': 'diclofenac sodium modafinil',
    'diclofenac potassium and modafinil': 'diclofenac potassium modafinil',
    'diclofenac sodium and armodafinil': 'diclofenac sodium armodafinil',
    'diclofenac potassium and armodafinil': 'diclofenac potassium armodafinil',
    'diclofenac sodium and methylphenidate': 'diclofenac sodium methylphenidate',
    'diclofenac potassium and methylphenidate': 'diclofenac potassium methylphenidate',
    'diclofenac sodium and dexmethylphenidate': 'diclofenac sodium dexmethylphenidate',
    'diclofenac potassium and dexmethylphenidate': 'diclofenac potassium dexmethylphenidate',
    'diclofenac sodium and amphetamine': 'diclofenac sodium amphetamine',
    'diclofenac potassium and amphetamine': 'diclofenac potassium amphetamine',
    'diclofenac sodium and dextroamphetamine': 'diclofenac sodium dextroamphetamine',
    'diclofenac potassium and dextroamphetamine': 'diclofenac potassium dextroamphetamine',
    'diclofenac sodium and lisdexamfetamine': 'diclofenac sodium lisdexamfetamine',
    'diclofenac potassium and lisdexamfetamine': 'diclofenac potassium lisdexamfetamine',
    'diclofenac sodium and methamphetamine': 'diclofenac sodium methamphetamine',
    'diclofenac potassium and methamphetamine': 'diclofenac potassium methamphetamine',
    'diclofenac sodium and pemoline': 'diclofenac sodium pemoline',
    'diclofenac potassium and pemoline': 'diclofenac potassium pemoline',
    'diclofenac sodium and caffeine': 'diclofenac sodium caffeine',
    'diclofenac potassium and caffeine': 'diclofenac potassium caffeine',
    'diclofenac sodium and nicotine': 'diclofenac sodium nicotine',
    'diclofenac potassium and nicotine': 'diclofenac potassium nicotine',
    'diclofenac sodium and varenicline': 'diclofenac sodium varenicline',
    'diclofenac potassium and varenicline': 'diclofenac potassium varenicline',
    'diclofenac sodium and bupropion': 'diclofenac sodium bupropion',
    'diclofenac potassium and bupropion': 'diclofenac potassium bupropion',
    'diclofenac sodium and nortriptyline': 'diclofenac sodium nortriptyline',
    'diclofenac potassium and nortriptyline': 'diclofenac potassium nortriptyline',
    'diclofenac sodium and clonidine': 'diclofenac sodium clonidine',
    'diclofenac potassium and clonidine': 'diclofenac potassium clonidine',
    'diclofenac sodium and mecamylamine': 'diclofenac sodium mecamylamine',
    'diclofenac potassium and mecamylamine': 'diclofenac potassium mecamylamine',
    'diclofenac sodium and lobeline': 'diclofenac sodium lobeline',
    'diclofenac potassium and lobeline': 'diclofenac potassium lobeline',
    'diclofenac sodium and cytisine': 'diclofenac sodium cytisine',
    'diclofenac potassium and cytisine': 'diclofenac potassium cytisine',
    'diclofenac sodium and galantamine': 'diclofenac sodium galantamine',
    'diclofenac potassium and galantamine': 'diclofenac potassium galantamine',
    'diclofenac sodium and rivastigmine': 'diclofenac sodium rivastigmine',
    'diclofenac potassium and rivastigmine': 'diclofenac potassium rivastigmine',
    'diclofenac sodium and donepezil': 'diclofenac sodium donepezil',
    'diclofenac potassium and donepezil': 'diclofenac potassium donepezil',
    'diclofenac sodium and memantine': 'diclofenac sodium memantine',
    'diclofenac potassium and memantine': 'diclofenac potassium memantine',
    'diclofenac sodium and tacrine': 'diclofenac sodium tacrine',
    'diclofenac potassium and tacrine': 'diclofenac potassium tacrine',
    'diclofenac sodium and physostigmine': 'diclofenac sodium physostigmine',
    'diclofenac potassium and physostigmine': 'diclofenac potassium physostigmine',
    'diclofenac sodium and neostigmine': 'diclofenac sodium neostigmine',
    'diclofenac potassium and neostigmine': 'diclofenac potassium neostigmine',
    'diclofenac sodium and pyridostigmine': 'diclofenac sodium pyridostigmine',
    'diclofenac potassium and pyridostigmine': 'diclofenac potassium pyridostigmine',
    'diclofenac sodium and edrophonium': 'diclofenac sodium edrophonium',
    'diclofenac potassium and edrophonium': 'diclofenac potassium edrophonium',
    'diclofenac sodium and ambenonium': 'diclofenac sodium ambenonium',
    'diclofenac potassium and ambenonium': 'diclofenac potassium ambenonium',
    'diclofenac sodium and distigmine': 'diclofenac sodium distigmine',
    'diclofenac potassium and distigmine': 'diclofenac potassium distigmine',
    'diclofenac sodium and demecarium': 'diclofenac sodium demecarium',
    'diclofenac potassium and demecarium': 'diclofenac potassium demecarium',
    'diclofenac sodium and echothiophate': 'diclofenac sodium echothiophate',
    'diclofenac potassium and echothiophate': 'diclofenac potassium echothiophate',
    'diclofenac sodium and isoflurophate': 'diclofenac sodium isoflurophate',
    'diclofenac potassium and isoflurophate': 'diclofenac potassium isoflurophate',
    'diclofenac sodium and malathion': 'diclofenac sodium malathion',
    'diclofenac potassium and malathion': 'diclofenac potassium malathion',
    'diclofenac sodium and parathion': 'diclofenac sodium parathion',
    'diclofenac potassium and parathion': 'diclofenac potassium parathion',
    'diclofenac sodium and diazinon': 'diclofenac sodium diazinon',
    'diclofenac potassium and diazinon': 'diclofenac potassium diazinon',
    'diclofenac sodium and chlorpyrifos': 'diclofenac sodium chlorpyrifos',
    'diclofenac potassium and chlorpyrifos': 'diclofenac potassium chlorpyrifos',
    'diclofenac sodium and dichlorvos': 'diclofenac sodium dichlorvos',
    'diclofenac potassium and dichlorvos': 'diclofenac potassium dichlorvos',
    'diclofenac sodium and trichlorfon': 'diclofenac sodium trichlorfon',
    'diclofenac potassium and trichlorfon': 'diclofenac potassium trichlorfon',
    'diclofenac sodium and fenthion': 'diclofenac sodium fenthion',
    'diclofenac potassium and fenthion': 'diclofenac potassium fenthion',
    'diclofenac sodium and temephos': 'diclofenac sodium temephos',
    'diclofenac potassium and temephos': 'diclofenac potassium temephos',
    'diclofenac sodium and phosmet': 'diclofenac sodium phosmet',
    'diclofenac potassium and phosmet': 'diclofenac potassium phosmet',
    'diclofenac sodium and dimethoate': 'diclofenac sodium dimethoate',
    'diclofenac potassium and dimethoate': 'diclofenac potassium dimethoate',
    'diclofenac sodium and methidathion': 'diclofenac sodium methidathion',
    'diclofenac potassium and methidathion': 'diclofenac potassium methidathion',
    'diclofenac sodium and oxydemeton-methyl': 'diclofenac sodium oxydemeton-methyl',
    'diclofenac potassium and oxydemeton-methyl': 'diclofenac potassium oxydemeton-methyl',
    'diclofenac sodium and phorate': 'diclofenac sodium phorate',
    'diclofenac potassium and phorate': 'diclofenac potassium phorate',
    'diclofenac sodium and terbufos': 'diclofenac sodium terbufos',
    'diclofenac potassium and terbufos': 'diclofenac potassium terbufos',
    'diclofenac sodium and disulfoton': 'diclofenac sodium disulfoton',
    'diclofenac potassium and disulfoton': 'diclofenac potassium disulfoton',
    'diclofenac sodium and ethion': 'diclofenac sodium ethion',
    'diclofenac potassium and ethion': 'diclofenac potassium ethion',
    'diclofenac sodium and profenofos': 'diclofenac sodium profenofos',
    'diclofenac potassium and profenofos': 'diclofenac potassium profenofos',
    'diclofenac sodium and prothiofos': 'diclofenac sodium prothiofos',
    'diclofenac potassium and prothiofos': 'diclofenac potassium prothiofos',
    'diclofenac sodium and isazofos': 'diclofenac sodium isazofos',
    'diclofenac potassium and isazofos': 'diclofenac potassium isazofos',
    'diclofenac sodium and isofenphos': 'diclofenac sodium isofenphos',
    'diclofenac potassium and isofenphos': 'diclofenac potassium isofenphos',
    'diclofenac sodium and phosalone': 'diclofenac sodium phosalone',
    'diclofenac potassium and phosalone': 'diclofenac potassium phosalone',
    'diclofenac sodium and azinphos-methyl': 'diclofenac sodium azinphos-methyl',
    'diclofenac potassium and azinphos-methyl': 'diclofenac potassium azinphos-methyl',
    'diclofenac sodium and azinphos-ethyl': 'diclofenac sodium azinphos-ethyl',
    'diclofenac potassium and azinphos-ethyl': 'diclofenac potassium azinphos-ethyl',
    'diclofenac sodium and coumaphos': 'diclofenac sodium coumaphos',
    'diclofenac potassium and coumaphos': 'diclofenac potassium coumaphos',
    'diclofenac sodium and crufomate': 'diclofenac sodium crufomate',
    'diclofenac potassium and crufomate': 'diclofenac potassium crufomate',
    'diclofenac sodium and famphur': 'diclofenac sodium famphur',
    'diclofenac potassium and famphur': 'diclofenac potassium famphur',
    'diclofenac sodium and fenamiphos': 'diclofenac sodium fenamiphos',
    'diclofenac potassium and fenamiphos': 'diclofenac potassium fenamiphos',
    'diclofenac sodium and fensulfothion': 'diclofenac sodium fensulfothion',
    'diclofenac potassium and fensulfothion': 'diclofenac potassium fensulfothion',
    'diclofenac sodium and fonofos': 'diclofenac sodium fonofos',
    'diclofenac potassium and fonofos': 'diclofenac potassium fonofos',
    'diclofenac sodium and mevinphos': 'diclofenac sodium mevinphos',
    'diclofenac potassium and mevinphos': 'diclofenac potassium mevinphos',
    'diclofenac sodium and naled': 'diclofenac sodium naled',
    'diclofenac potassium and naled': 'diclofenac potassium naled',
    'diclofenac sodium and parathion-methyl': 'diclofenac sodium parathion-methyl',
    'diclofenac potassium and parathion-methyl': 'diclofenac potassium parathion-methyl',
    'diclofenac sodium and phosfolan': 'diclofenac sodium phosfolan',
    'diclofenac potassium and phosfolan': 'diclofenac potassium phosfolan',
    'diclofenac sodium and phosmet': 'diclofenac sodium phosmet',
    'diclofenac potassium and phosmet': 'diclofenac potassium phosmet',
    'diclofenac sodium and phosphamidon': 'diclofenac sodium phosphamidon',
    'diclofenac potassium and phosphamidon': 'diclofenac potassium phosphamidon',
    'diclofenac sodium and pirimiphos-methyl': 'diclofenac sodium pirimiphos-methyl',
    'diclofenac potassium and pirimiphos-methyl': 'diclofenac potassium pirimiphos-methyl',
    'diclofenac sodium and quinalphos': 'diclofenac sodium quinalphos',
    'diclofenac potassium and quinalphos': 'diclofenac potassium quinalphos',
    'diclofenac sodium and sulfotep': 'diclofenac sodium sulfotep',
    'diclofenac potassium and sulfotep': 'diclofenac potassium sulfotep',
    'diclofenac sodium and tebupirimfos': 'diclofenac sodium tebupirimfos',
    'diclofenac potassium and tebupirimfos': 'diclofenac potassium tebupirimfos',
    'diclofenac sodium and temephos': 'diclofenac sodium temephos',
    'diclofenac potassium and temephos': 'diclofenac potassium temephos',
    'diclofenac sodium and terbufos': 'diclofenac sodium terbufos',
    'diclofenac potassium and terbufos': 'diclofenac potassium terbufos',
    'diclofenac sodium and tetrachlorvinphos': 'diclofenac sodium tetrachlorvinphos',
    'diclofenac potassium and tetrachlorvinphos': 'diclofenac potassium tetrachlorvinphos',
    'diclofenac sodium and thiometon': 'diclofenac sodium thiometon',
    'diclofenac potassium and thiometon': 'diclofenac potassium thiometon',
    'diclofenac sodium and triazophos': 'diclofenac sodium triazophos',
    'diclofenac potassium and triazophos': 'diclofenac potassium triazophos',
    'diclofenac sodium and trichlorfon': 'diclofenac sodium trichlorfon',
    'diclofenac potassium and trichlorfon': 'diclofenac potassium trichlorfon',
    'diclofenac sodium and vamidothion': 'diclofenac sodium vamidothion',
    'diclofenac potassium and vamidothion': 'diclofenac potassium vamidothion',
    'diclofenac sodium and aldicarb': 'diclofenac sodium aldicarb',
    'diclofenac potassium and aldicarb': 'diclofenac potassium aldicarb',
    'diclofenac sodium and bendiocarb': 'diclofenac sodium bendiocarb',
    'diclofenac potassium and bendiocarb': 'diclofenac potassium bendiocarb'
    }
